CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(64) NULL,
  phone VARCHAR(32) NULL,
  country VARCHAR(100) NULL,
  title VARCHAR(32) NULL,
  first_name VARCHAR(255) NULL,
  middle_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  position VARCHAR(100) NULL,
  institution VARCHAR(255) NULL,
  department VARCHAR(255) NULL,
  grade_level VARCHAR(100) NULL,
  school_name VARCHAR(255) NULL,
  school_email VARCHAR(255) NULL,
  admission_number VARCHAR(100) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  postal_code VARCHAR(32) NULL,
  reviewer_experience_text TEXT NULL,
  reviewer_reason_text TEXT NULL,
  reviewer_weekly_availability VARCHAR(32) NULL,
  reviewer_profile_links TEXT NULL,
  reviewer_cv_path VARCHAR(1024) NULL,
  reviewer_cv_original_name VARCHAR(255) NULL,
  reviewer_cv_mime VARCHAR(100) NULL,
  reviewer_cv_size INT NULL,
  reviewer_supporting_documents_json TEXT NULL,
  reviewer_declaration_confirmed BOOLEAN NULL DEFAULT false,
  reset_token VARCHAR(255) NULL,
  reset_expires TIMESTAMP NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  assigned_journals_json TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (email),
  UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS paper_submissions (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slug VARCHAR(255) NOT NULL,
  title VARCHAR(500) NOT NULL,
  authors TEXT NOT NULL,
  abstract TEXT NOT NULL,
  author_bio TEXT NULL,
  submission_details TEXT NULL,
  keywords VARCHAR(500) NULL,
  category VARCHAR(255) NULL,
  authors_json TEXT NULL,
  eissn VARCHAR(100) DEFAULT '2833-8022',
  accepted_at TIMESTAMP NULL,
  revised_at TIMESTAMP NULL,
  corresponding_author_email VARCHAR(255) NULL,
  doi VARCHAR(100) NULL UNIQUE,
  funding_info TEXT NULL,
  license_url VARCHAR(255) DEFAULT 'https://creativecommons.org/licenses/by/4.0/',
  volume_year INT NULL,
  issue_number INT NULL,
  tracking_id VARCHAR(64) NULL,
  tracking_country3 CHAR(3) NULL,
  tracking_year INT NULL,
  tracking_seq INT NULL,
  manuscript_path VARCHAR(1024) NOT NULL,
  manuscript_original_name VARCHAR(255) NOT NULL,
  manuscript_mime VARCHAR(100) NOT NULL,
  manuscript_size INT NOT NULL,
  version INT NOT NULL DEFAULT 1,
  view_count INT NOT NULL DEFAULT 0,
  download_count INT NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'submitted',
  admin_comment TEXT NULL,
  assigned_admin_ids_json TEXT NULL,
  reviewed_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMP NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (slug),
  UNIQUE (tracking_id),
  UNIQUE (tracking_year, tracking_seq)
);

CREATE TABLE IF NOT EXISTS paper_submission_versions (
  id SERIAL PRIMARY KEY,
  paper_submission_id INT NOT NULL REFERENCES paper_submissions(id) ON DELETE CASCADE,
  version_number INT NOT NULL,
  title VARCHAR(500) NOT NULL,
  authors TEXT NOT NULL,
  abstract TEXT NOT NULL,
  author_bio TEXT NULL,
  submission_details TEXT NULL,
  keywords VARCHAR(500) NULL,
  category VARCHAR(255) NULL,
  authors_json TEXT NULL,
  eissn VARCHAR(100) DEFAULT '2833-8022',
  accepted_at TIMESTAMP NULL,
  revised_at TIMESTAMP NULL,
  corresponding_author_email VARCHAR(255) NULL,
  manuscript_path VARCHAR(1024) NOT NULL,
  manuscript_original_name VARCHAR(255) NOT NULL,
  manuscript_mime VARCHAR(100) NOT NULL,
  manuscript_size INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'submitted',
  admin_comment TEXT NULL,
  reviewed_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMP NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paper_submission_attachments (
  id SERIAL PRIMARY KEY,
  paper_submission_id INT NOT NULL REFERENCES paper_submissions(id) ON DELETE CASCADE,
  version_number INT NOT NULL DEFAULT 1,
  category VARCHAR(255) NOT NULL DEFAULT 'Manuscript',
  description VARCHAR(500) NULL,
  file_path VARCHAR(1024) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_applications (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  assigned_journals_json TEXT NULL,
  country VARCHAR(100) NULL,
  institution VARCHAR(255) NULL,
  grade_level VARCHAR(100) NULL,
  reviewer_experience_text TEXT NULL,
  reviewer_reason_text TEXT NULL,
  reviewer_weekly_availability VARCHAR(32) NULL,
  reviewer_profile_links TEXT NULL,
  reviewer_cv_path VARCHAR(1024) NULL,
  reviewer_cv_original_name VARCHAR(255) NULL,
  reviewer_cv_mime VARCHAR(100) NULL,
  reviewer_cv_size INT NULL,
  reviewer_supporting_documents_json TEXT NULL,
  reviewer_declaration_confirmed BOOLEAN NULL DEFAULT false,
  cv_path VARCHAR(1024) NOT NULL,
  cv_original_name VARCHAR(255) NOT NULL,
  cv_mime VARCHAR(100) NOT NULL,
  cv_size INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  reviewed_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
